#%RAML 0.8
title: Instructors
version: v1.0.0
baseUri: http://github.com/org/folio/mod-waitlist

documentation:
  - title: mod-waitlist Instructors API
    content: This documents the API calls that can be made to query and manage instructors.

schemas: 
  - instructor: !include schemas/instructor.json
  - instructorCollection: !include schemas/instructorCollection.json
  - errors: !include raml-util/schemas/errors.schema
  - error: !include raml-util/schemas/error.schema
  - parameters: !include raml-util/schemas/parameters.schema

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable: !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml
  - validate: !include raml-util/traits/validation.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml

/instructors:
  type:
    collection:
      exampleCollection: !include examples/instructorCollection.json
      exampleItem: !include examples/instructor.json
      schemaCollection: instructorCollection
      schemaItem: instructor
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Returns a list of instructors.
  post:
    description: Posts an instructor.
